export const NomenclaturesConstants = {
    

    GETALL_POSTES:  'NOMCL_GETALL_POSTES',
    GETALL_DIPLOMES: 'NOMCL_GETALL_DIPLOMES',
    GETALL_DOMAINES: 'NOMCL_GETALL_DOMAINES',
    GETALL_ETABLISSEMENTS: 'NOMCL_GETALL_ETABLISSEMENTS',
    GETALL_SPECIALITES: 'NOMCL_GETALL_SPECIALITES',
    GETALL_ETAT_CIVIL: 'NOMCL_GETALL_ETAT_CIVIL',
    GETALL_TYPES_CONDIDATURES: 'NOMCL_GETALL_TYPES_CONDIDATURES',
    GETALL_PAYS: 'NOMCL_GETALL_PAYS',
    GETALL_MODULES:'NOMCL_GETALL_MODULES'
     
};
